version: '2'

services:
  prodapi: 
    environment:
      NODE_ENV: 'production'
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8080"
    command: sh -c "cd broker-api && npm install && tsc && node ./dist/app.js"
