version: '2'

services:
  prodapi: 
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8080"
    command: sh -c "cd broker-api && npm install && tsc && nodemon --delay 500ms ./dist/app.js"
