api:
  build: .
  links:
    - 'mongo:mongo'
  environment:
    NODE_ENV: 'development'
  volumes:
    - .:/app
    - /app/node_modules
  ports:
    - "0.0.0.0:9000:9000"
  command: sh -c "mkdir -p dist && touch ./dist/app.js && nodemon --delay 500ms ./dist/app.js"

transpiler:
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  command: ["tsc", "-w"]

linter:
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  command: nodemon --delay 500ms --exec "find . -path ./ -prune -o -path ./node_modules -prune -o -path ./dist -prune -o -name '*.ts' -print | xargs tslint"

mongo:
  image: mvertes/alpine-mongo:3.2.1
  ports:
    - "27017"
  command: ["mongod"]

mocha:
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  links:
    - 'mongo:mongo'
  command: nodemon --delay 500ms --exec 'mocha --recursive --bail --colors' ./dist
  environment:
    NODE_ENV: 'test'
